---
baseURL: "/test-docs/enterprise/"
languageCode: "en-us"
title: "Camunda Enterprise"
theme: "camunda"

relativeURLs: true

blackfriday:
  plainIDAnchors: true

params:
  canonicalBasePath: "https://docs.camunda.org"
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "/test-docs/get-started"
    - id: "user-guide"
      name: "Camunda 7"
      url: "/test-docs/user-guide"
    - id: "enterprise"
      name: "Enterprise"
      url: "/test-docs/enterprise"
    - id: "security"
      name: "Security"
      url: "/test-docs/security"
  section:
    id: "enterprise"
  github:
    repositoryName: "camunda/camunda-docs-static"
    branch: "master/enterprise"

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"

disableKinds:
- taxonomy
- taxonomyTerm
...
